routes/admin.php
Route::post('plans/batch_action', 'PlanController@batchAction')->name('plans.batch_action');

Route::resource('plans', 'PlanController', [
        'only' => ['index', 'create', 'store', 'update', 'destroy'],
]);


/*
|--------------------------------------------------------------------------
| Keywords module
|--------------------------------------------------------------------------
|
| Route for Keywords module
|
*/

Route::post('keywords/search', 'KeywordController@search')->name('keywords.search');
Route::get('keywords/export', 'KeywordController@export')->name('keywords.export');
Route::get('keywords/{keyword}/show', 'KeywordController@show')->name('keywords.show');
Route::post('keywords/{keyword}/remove-mms', 'KeywordController@removeMMS')->name('keywords.remove-mms');
Route::post('keywords/batch_action', 'KeywordController@batchAction')->name('keywords.batch_action');

Route::resource('keywords', 'KeywordController', [
        'only' => ['index', 'create', 'store', 'update', 'destroy'],
]);


/*
|--------------------------------------------------------------------------
| Sender id module
|--------------------------------------------------------------------------
|
| Route for sender id and sender id plan module
|
*/

Route::post('senderid/search', 'SenderIDController@search')->name('senderid.search');
Route::get('senderid/export', 'SenderIDController@export')->name('senderid.export');
Route::get('senderid/{senderid}/show', 'SenderIDController@show')->name('senderid.show');
Route::post('senderid/{senderid}/active', 'SenderIDController@activeToggle')->name('senderid.active');
Route::post('senderid/batch_action', 'SenderIDController@batchAction')->name('senderid.batch_action');
Route::resource('senderid', 'SenderIDController', [
        'only' => ['index', 'create', 'store', 'update', 'destroy'],
]);

Route::get('senderid/plan', 'SenderIDController@plan')->name('senderid.plan');
Route::post('senderid/search-plan', 'SenderIDController@searchPlan')->name('senderid.search_plan');
Route::get('senderid/create-plan', 'SenderIDController@createPlan')->name('senderid.create_plan');
Route::post('senderid/store-plan', 'SenderIDController@storePlan')->name('senderid.store_plan');
Route::post('senderid/delete-plan/{plan}', 'SenderIDController@deletePlan')->name('senderid.delete_plan');
Route::post('senderid/delete-batch-plan', 'SenderIDController@deleteBatchPlan')->name('senderid.delete_batch_plan');


/*
|--------------------------------------------------------------------------
| Phone number module
|--------------------------------------------------------------------------
|
| Route for phone number module
|
*/

Route::post('phone-numbers/search', 'PhoneNumberController@search')->name('phone-numbers.search');
Route::get('phone-numbers/export', 'PhoneNumberController@export')->name('phone-numbers.export');
Route::get('phone-numbers/{number}/show', 'PhoneNumberController@show')->name('phone-numbers.show');
Route::post('phone-numbers/batch_action', 'PhoneNumberController@batchAction')->name('phone-numbers.batch_action');
Route::resource('phone-numbers', 'PhoneNumberController', [
        'only' => ['index', 'create', 'store', 'update', 'destroy'],
]);

// Template tags Module Routes
Route::post('tags/search', 'TemplateTagsController@search')->name('tags.search');
Route::get('tags/export', 'TemplateTagsController@export')->name('tags.export');
Route::get('tags/{tag}/show', 'TemplateTagsController@show')->name('tags.show');
Route::post('tags/{tag}/active', 'TemplateTagsController@activeToggle')->name('tags.active');
Route::post('tags/batch_action', 'TemplateTagsController@batchAction')->name('tags.batch_action');
Route::resource('tags', 'TemplateTagsController', [
        'only' => ['index', 'create', 'store', 'update', 'destroy'],
]);


/*
|-------------------------------------------------------------------------
| Security module
|-------------------------------------------------------------------------
|
| working with blacklists and spam word features in this module
|
*/

// Blacklists Module Routes
Route::post('blacklists/search', 'BlacklistsController@search')->name('blacklists.search');
Route::get('blacklists/export', 'BlacklistsController@export')->name('blacklists.export');
Route::post('blacklists/batch_action', 'BlacklistsController@batchAction')->name('blacklists.batch_action');
Route::resource('blacklists', 'BlacklistsController', [
        'only' => ['index', 'create', 'store', 'destroy'],
]);


// Spam word Module Routes
Route::post('spam-word/search', 'SpamWordController@search')->name('spam-word.search');
Route::get('spam-word/export', 'SpamWordController@export')->name('spam-word.export');
Route::post('spam-word/batch_action', 'SpamWordController@batchAction')->name('spam-word.batch_action');
Route::resource('spam-word', 'SpamWordController', [
        'only' => ['index', 'create', 'store', 'destroy'],
]);


/*
|--------------------------------------------------------------------------
| Administrator Module
|--------------------------------------------------------------------------
|
| working with different types of admin and associate admin role
|
*/

//Admin Role Module
Route::post('roles/search', 'RoleController@search')->name('roles.search');
Route::get('roles/export', 'RoleController@export')->name('roles.export');
Route::get('roles/{role}/show', 'RoleController@show')->name('roles.show');
Route::post('roles/{role}/active', 'RoleController@activeToggle')->name('roles.active');
Route::post('roles/batch_action', 'RoleController@batchAction')->name('roles.batch_action');
Route::resource('roles', 'RoleController', [
        'only' => ['index', 'create', 'store', 'update', 'destroy'],
]);

//Administrator Module
Route::post('administrators/search', 'AdministratorController@search')->name('administrators.search');
Route::get('administrators/export', 'AdministratorController@export')->name('administrators.export');
Route::get('administrators/{administrator}/show', 'AdministratorController@show')->name('administrators.show');
Route::post('administrators/{administrator}/active', 'AdministratorController@activeToggle')->name('administrators.active');
Route::post('administrators/batch_action', 'AdministratorController@batchAction')->name('administrators.batch_action');
Route::resource('administrators', 'AdministratorController', [
        'only' => ['index', 'create', 'store', 'update', 'destroy'],
]);


/*
|--------------------------------------------------------------------------
| settings module
|--------------------------------------------------------------------------
|
| All settings related routes describe here
|
*/

//All Settings
Route::get('settings', 'SettingsController@general')->name('settings.general');
Route::post('settings', 'SettingsController@postGeneral');
Route::post('settings/email', 'SettingsController@email')->name('settings.email');
Route::post('settings/authentication', 'SettingsController@authentication')->name('settings.authentication');
Route::post('settings/notifications', 'SettingsController@notifications')->name('settings.notifications');
Route::post('settings/pusher', 'SettingsController@pusher')->name('settings.pusher');
Route::post('settings/license', 'SettingsController@license')->name('settings.license');

//Language module
Route::post('languages/{language}/active', 'LanguageController@activeToggle')->name('languages.active');
Route::get('languages/{language}/download', 'LanguageController@download')->name('languages.download');
Route::get('languages/{language}/upload', 'LanguageController@upload')->name('languages.upload');
Route::post('languages/{language}/upload', 'LanguageController@uploadLanguage');
Route::get('languages/{language}/show', 'LanguageController@show')->name('languages.show');

Route::resource('languages', 'LanguageController', [
        'only' => ['index', 'create', 'store', 'update', 'destroy'],
]);


// Payment gateways
Route::post('payment-gateways/{gateway}/active', 'PaymentMethodController@activeToggle')->name('payment-gateways.active');
Route::get('payment-gateways/{gateway}/show', 'PaymentMethodController@show')->name('payment-gateways.show');

Route::resource('payment-gateways', 'PaymentMethodController', [
        'only' => ['index', 'update'],
]);

// Email Templates
Route::post('email-templates/{template}/active', 'EmailTemplateController@activeToggle')->name('email-templates.active');
Route::get('email-templates/{template}/show', 'EmailTemplateController@show')->name('email-templates.show');

Route::resource('email-templates', 'EmailTemplateController', [
        'only' => ['index', 'update'],
]);


//Maintenance Mode
Route::get('maintenance-mode', 'SettingsController@maintenanceMode')->name('settings.maintenance_mode');

//update application
Route::get('update-application', 'SettingsController@updateApplication')->name('settings.update_application');

//Plugins
Route::get('plugins', 'PluginsController@plugins')->name('plugins');


Route::post('invoices/search', 'InvoiceController@search')->name('invoices.search');
Route::get('invoices/{invoice}/view', 'InvoiceController@view')->name('invoices.view');
Route::post('invoices/batch_action', 'InvoiceController@batchAction')->name('invoices.batch_action');
Route::resource('invoices', 'InvoiceController', [
        'only' => ['index', 'destroy'],
]);


/*
|--------------------------------------------------------------------------
| Reports module
|--------------------------------------------------------------------------
|
|
|
*/

Route::prefix('reports')->name('reports.')->group(function () {
    Route::get('/', 'ReportsController@reports')->name('all');
    Route::post('/search', 'ReportsController@searchAllMessages')->name('search.all');
    Route::post('/{uid}/view', 'ReportsController@viewReports');
    Route::get('/export', 'ReportsController@export')->name('export');
    Route::post('/{uid}/destroy', 'ReportsController@destroy');

routes/web.php
<?php

use App\Http\Controllers\LanguageController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {

    if (config('app.stage') == 'new') {
        return redirect('install');
    }

    if (config('app.stage') == 'Live' && config('app.version') == '2.8') {
        return redirect('update');
    }

    return redirect('login');
});

// locale Route
Route::get('lang/{locale}', [LanguageController::class, 'swap']);
Route::any('languages', [LanguageController::class, 'languages'])->name('languages');

Route::get('test', function (){
    event(new \App\Events\MessageReceived('hello world'));
});

resources/views/admin/administrator/create.blade.php
@extends('layouts/contentLayoutMaster')

@section('title', __('locale.administrator.create_administrator'))

@section('vendor-style')
    <!-- vendor css files -->
    <link rel="stylesheet" href="{{ asset(mix('vendors/css/forms/select/select2.min.css')) }}">
@endsection

@section('content')
    <!-- Basic Vertical form layout section start -->
    <section id="basic-vertical-layouts">
        <div class="row match-height">
            <div class="col-md-6 col-12">

                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title">{{ __('locale.administrator.create_administrator') }}</h4>
                    </div>
                    <div class="card-content">
                        <div class="card-body">
                            <form class="form form-vertical" action="{{ route('admin.administrators.store') }}" method="post" enctype="multipart/form-data">
                                @csrf
                                <div class="row">

                                    <div class="col-12">
                                        <div class="form-group">
                                            <label for="email" class="required">{{__('locale.labels.email')}}</label>
                                            <input type="email" id="email" class="form-control @error('email') is-invalid @enderror" value="{{ old('email') }}" name="email" required>
                                            @error('email')
                                            <div class="invalid-feedback">
                                                {{ $message }}
                                            </div>
                                            @enderror
                                        </div>
                                    </div>


                                    <div class="col-12 form-group">
                                        <label for="password" class="required">{{__('locale.labels.password')}}</label>
                                        <div class="position-relative show_hide_password">
                                            <input type="password" id="password" class="form-control @error('password') is-invalid @enderror" value="{{ old('password') }}" name="password" required>
                                            <div class="form-control-position cursor-pointer">
                                                <i class="feather icon-eye-off"></i>
                                            </div>
                                            @error('password')
                                            <div class="invalid-feedback">
                                                {{ $message }}
                                            </div>
                                            @enderror
                                        </div>
                                    </div>

                                    <div class="col-12">
                                        <div class="form-group">
                                            <label for="password_confirmation" class="required">{{__('locale.labels.password_confirmation')}}</label>
                                            <div class="position-relative show_hide_password">
                                                <input type="password" id="password_confirmation"
                                                       class="form-control @error('password_confirmation') is-invalid @enderror"
                                                       value="{{ old('password_confirmation') }}"
                                                       name="password_confirmation" required>
                                                <div class="form-control-position cursor-pointer">
                                                    <i class="feather icon-eye-off"></i>
                                                </div>
                                                @error('password_confirmation')
                                                <div class="invalid-feedback">
                                                    {{ $message }}
                                                </div>
                                                @enderror
                                            </div>
                                        </div>
                                    </div>

                                    <div class="col-12">
                                        <div class="form-group">
                                            <label for="first_name" class="required">{{__('locale.labels.first_name')}}</label>
                                            <input type="text" id="first_name" class="form-control @error('first_name') is-invalid @enderror" value="{{ old('first_name') }}" name="first_name" required>
                                            @error('first_name')
                                            <div class="invalid-feedback">
                                                {{ $message }}
                                            </div>
                                            @enderror
                                        </div>
                                    </div>

                                    <div class="col-12">
                                        <div class="form-group">
                                            <label for="last_name">{{__('locale.labels.last_name')}}</label>
                                            <input type="text" id="last_name" class="form-control @error('last_name') is-invalid @enderror" value="{{ old('last_name') }}" name="last_name">
                                            @error('last_name')
                                            <div class="invalid-feedback">
                                                {{ $message }}
                                            </div>
                                            @enderror
                                        </div>
                                    </div>

                                    <div class="col-12">
                                        <div class="form-group">
                                            <label for="phone" class="required">{{__('locale.labels.phone')}}</label>
                                            <input type="number" id="phone" class="form-control @error('phone') is-invalid @enderror" value="{{ old('phone') }}" name="phone" required>
                                            @error('phone')
                                            <div class="invalid-feedback">
                                                {{ $message }}
                                            </div>
                                            @enderror
                                        </div>
                                    </div>


                                    <div class="col-12">
                                        <fieldset class="form-group">
                                            <label for="role" class="required">{{__('locale.labels.roles')}}</label>
                                            <select class="form-control select2" id="role" name="roles[]">
                                                @foreach($roles as $role)
                                                    <option value="{{ $role->id }}"> {{ $role->name }}</option>
                                                @endforeach
                                            </select>
                                        </fieldset>
                                        @error('roles')
                                        <div class="text-danger">
                                            {{ $message }}
                                        </div>
                                        @enderror
                                    </div>

                                    <div class="col-12">
                                        <div class="form-group">
                                            <label for="status" class="required">{{ __('locale.labels.status') }}</label>
                                            <select class="form-control" name="status" id="status">
                                                <option value="1">{{ __('locale.labels.active') }}</option>
                                                <option value="0">{{ __('locale.labels.inactive')}} </option>
                                            </select>
                                            @error('status')
                                            <div class="text-danger">
                                                {{ $message }}
                                            </div>
                                            @enderror
                                        </div>
                                    </div>

                                    <div class="col-12">
                                        <div class="form-group">
                                            <label for="image">{{ __('locale.labels.image') }}</label>
                                            <div class="custom-file">
                                                <input type="file" name="image" class="custom-file-input" id="image" accept="image/*">
                                                <label class="custom-file-label" for="image" data-browse="{{ __('locale.labels.browse') }}">{{__('locale.labels.choose_file')}}</label>
                                                @error('image')
                                                <div class="text-danger">
                                                    {{ $message }}
                                                </div>
                                                @enderror
                                            </div>
                                            <p><small class="text-primary"> {{__('locale.customer.profile_image_size')}} </small></p>
                                        </div>
                                    </div>

                                    <div class="col-12">
                                        <div class="form-group">
                                            <div class="custom-control custom-switch switch-md custom-switch-success mr-2 mb-1">
                                                <p class="mb-0">{{ __('locale.administrator.create_customer_account') }}?</p>
                                                <p><small class="text-primary">{{ __('locale.administrator.create_customer_account_associated_admin') }}</small></p>
                                                <input type="checkbox" name="is_customer" class="custom-control-input" id="customer">
                                                <label class="custom-control-label" for="customer">
                                                    <span class="switch-text-left">{{ __('locale.labels.yes') }}</span>
                                                    <span class="switch-text-right">{{ __('locale.labels.no') }}</span>
                                                </label>
                                            </div>
                                        </div>
                                    </div>


                                    <div class="col-12">
                                        <input type="hidden" value="1" name="is_admin">
                                        <button type="submit" class="btn btn-primary mr-1 mb-1">
                                            <i class="feather icon-save"></i> {{__('locale.buttons.save')}}
                                        </button>
                                    </div>


                                </div>
                            </form>
                        </div>

                    </div>
                </div>
            </div>


        </div>
    </section>
    <!-- // Basic Vertical form layout section end -->


@endsection


@section('vendor-script')
    <!-- vendor files -->
    <script src="{{ asset(mix('vendors/js/forms/select/select2.full.min.js')) }}"></script>
@endsection


@section('page-script')

    <script>
        let firstInvalid = $('form').find('.is-invalid').eq(0);
        let showHideInput = $('.show_hide_password input');
        let showHideIcon = $('.show_hide_password i');

        if (firstInvalid.length) {
            $('body, html').stop(true, true).animate({
                'scrollTop': firstInvalid.offset().top - 200 + 'px'
            }, 200);
        }

        // Basic Select2 select
        $(".select2").select2({
            // the following code is used to disable x-scrollbar when click in select input and
            // take 100% width in responsive also
            dropdownAutoWidth: true,
            width: '100%'
        });


        $(".form-control-position").on('click', function (event) {
            event.preventDefault();
            if (showHideInput.attr("type") === "text") {
                showHideInput.attr('type', 'password');
                showHideIcon.addClass("icon-eye-off");
                showHideIcon.removeClass("icon-eye");
            } else if (showHideInput.attr("type") === "password") {
                showHideInput.attr('type', 'text');
                showHideIcon.removeClass("icon-eye-off");
                showHideIcon.addClass("icon-eye");
            }
        });
    </script>
@endsection