routes/admin.php
<?php
/*
 * All routes for admin portal
 *
 * Item Name: Ultimate SMS - Bulk SMS Application For Marketing
 * Author: Codeglen
 * Author URL: https://codecanyon.net/user/codeglen
 */

Route::get('/dashboard', 'AdminBaseController@index')->name('home');

/*
|--------------------------------------------------------------------------
| Customer module
|--------------------------------------------------------------------------
|
| Route for Customer module
|
*/

Route::post('customers/search', 'CustomerController@search')->name('customers.search');
Route::get('customers/export', 'CustomerController@export')->name('customers.export');
Route::get('customers/{customer}/show', 'CustomerController@show')->name('customers.show');
Route::get('customers/{customer}/login-as', 'CustomerController@show')->name('customers.login_as');
Route::get('customers/{customer}/assign-plan', 'CustomerController@show')->name('customers.assign_plan');
Route::get('customers/{customer}/avatar', 'CustomerController@avatar')->name('customers.avatar');
Route::post('customers/{customer}/avatar', 'CustomerController@updateAvatar');
Route::post('customers/{customer}/remove-avatar', 'CustomerController@removeAvatar');
Route::post('customers/{customer}/add-unit', 'CustomerController@addUnit')->name('customers.add_unit');
Route::post('customers/{customer}/update-information', 'CustomerController@updateInformation')->name('customers.update_information');
Route::post('customers/{customer}/permissions', 'CustomerController@permissions')->name('customers.permissions');
Route::post('customers/{customer}/active', 'CustomerController@activeToggle')->name('customers.active');
Route::post('customers/batch_action', 'CustomerController@batchAction')->name('customers.batch_action');

Route::resource('customers', 'CustomerController', [
        'only' => ['index', 'create', 'store', 'update', 'destroy'],
]);

/*
|--------------------------------------------------------------------------
| Subscription module
|--------------------------------------------------------------------------
|
| Route for Subscription module
|
*/

Route::post('subscriptions/search', 'SubscriptionController@search')->name('subscriptions.search');
Route::post('subscriptions/{subscription}/approve-pending', 'SubscriptionController@approvePending')->name('subscriptions.approve_pending');
Route::post('subscriptions/{subscription}/reject-pending', 'SubscriptionController@rejectPending')->name('subscriptions.reject_pending');
Route::post('subscriptions/{subscription}/renew', 'SubscriptionController@renew')->name('subscriptions.renew');
Route::post('subscriptions/{subscription}/cancel', 'SubscriptionController@cancel')->name('subscriptions.cancel');
Route::get('subscriptions/{subscription}/logs', 'SubscriptionController@logs')->name('subscriptions.logs');
Route::get('subscriptions/{subscription}/change-plan', 'SubscriptionController@changePlan')->name('subscriptions.change_plan');
Route::post('subscriptions/{subscription}/change-plan', 'SubscriptionController@changePlan');
Route::post('subscriptions/batch_action', 'SubscriptionController@batchAction')->name('subscriptions.batch_action');

Route::resource('subscriptions', 'SubscriptionController', [
        'only' => ['index', 'create', 'store', 'destroy'],
]);

/*
|--------------------------------------------------------------------------
| Currency module
|--------------------------------------------------------------------------
|
| Route for Currency module
|
*/

Route::post('currencies/search', 'CurrencyController@search')->name('currencies.search');
Route::get('currencies/export', 'CurrencyController@export')->name('currencies.export');
Route::get('currencies/{currency}/show', 'CurrencyController@show')->name('currencies.show');
Route::post('currencies/{currency}/active', 'CurrencyController@activeToggle')->name('currencies.active');
Route::post('currencies/batch_action', 'CurrencyController@batchAction')->name('currencies.batch_action');

Route::resource('currencies', 'CurrencyController', [
        'only' => ['index', 'create', 'store', 'update', 'destroy'],
]);

/*
|--------------------------------------------------------------------------
| Sending servers module
|--------------------------------------------------------------------------
|
| Route for Sending servers module
|
*/

Route::post('sending-servers/search', 'SendingServerController@search')->name('sending-servers.search');
Route::get('sending-servers/select', 'SendingServerController@select')->name('sending-servers.select');
Route::get('sending-servers/create/{type}', 'SendingServerController@create')->name('sending-servers.create');
Route::get('sending-servers/export', 'SendingServerController@export')->name('sending-servers.export');
Route::get('sending-servers/{server}/show', 'SendingServerController@show')->name('sending-servers.show');
Route::post('sending-servers/{server}/active', 'SendingServerController@activeToggle')->name('sending-servers.active');
Route::post('sending-servers/custom-server/create', 'SendingServerController@addCustomServer')->name('sending-servers.add.custom');
Route::post('sending-servers/custom-server/update/{sending_server}', 'SendingServerController@updateCustomServer')->name('sending-servers.update.custom');
Route::post('sending-servers/batch_action', 'SendingServerController@batchAction')->name('sending-servers.batch_action');

Route::resource('sending-servers', 'SendingServerController', [
        'only' => ['index', 'store', 'update', 'destroy'],
]);


//Plan For Plan module
/**
 * Plan details
 * 1. Name of plan
 * 2. Price for plan
 * 3. description (optional)
 * 4. Billing cycle (Daily, Monthly, yearly, custom - [integer amount with day, week, month, year]
 * 5. Currency
 * 6. Billing Information (optional)
 *
 * Quota
 * 1. SMS Sending Credits
 * 2. Max List/Phone book
 * 3. Max Subscriber
 * 4. Max subscriber per list
 *
 * Plan features
 * 1. Customer can import list
 * 2. Customer can export list
 * 3. Customer can use API
 * 4. Customer can create own sending server
 * 5. Customer can create sub accounts
 * 6. Customer can delete sms history
 * 7. Add Previous sms balance on next subscription
 * 8. Sender ID Verification
 *
 * Pricing
 * 1. Coverage country
 * 2. plain, voice, mms, whatsapp message price
 *
 *Speed Limit
 * 1. Set a limit [unlimited, 100 sms per minute, 10000 sms per hour, 10000 sms per hour, 10,000 sms per day, 50,000 sms per day, custom - Sending Credits - Time Value - Time unit]
 * 2. Max Number of processes [1,2,3]
 *
 * Sending Servers
 * 1. Add multiple sending server (Rotate sending server when message will send)
 * 2. Set probability
 *
 */

Route::post('plans/search', 'PlanController@search')->name('plans.search');
Route::get('plans/export', 'PlanController@export')->name('plans.export');
Route::get('plans/{plan}/show', 'PlanController@show')->name('plans.show');
Route::post('plans/{plan}/active', 'PlanController@activeToggle')->name('plans.active');
Route::post('plans/{plan}/settings', 'PlanController@settingFeatures')->name('plans.settings.features');
Route::post('plans/{plan}/sending-servers', 'PlanController@addSendingServers')->name('plans.settings.sending-servers');
Route::post('plans/{plan}/update-fitness', 'PlanController@updateFitness')->name('plans.settings.update-fitness');
Route::post('plans/{plan}/set-primary', 'PlanController@setPrimary')->name('plans.settings.set-primary');
Route::post('plans/{plan}/speed-limit', 'PlanController@updateSpeedLimit')->name('plans.settings.speed-limit');
Route::post('plans/{plan}/cutting-system', 'PlanController@updateCuttingSystem')->name('plans.settings.cutting-system');
Route::post('plans/{plan}/pricing', 'PlanController@updatePricing')->name('plans.settings.pricing');
Route::post('plans/{plan}/delete-sending-server', 'PlanController@deletePlanSendingServer')->name('plans.settings.delete-sending-server');
Route::post('plans/{plan}/copy', 'PlanController@copy')->name('plans.copy');
Route::post('plans/batch_action', 'PlanController@batchAction')->name('plans.batch_action');

Route::resource('plans', 'PlanController', [
        'only' => ['index', 'create', 'store', 'update', 'destroy'],
]);


/*
|--------------------------------------------------------------------------
| Keywords module
|--------------------------------------------------------------------------
|
| Route for Keywords module
|
*/

Route::post('keywords/search', 'KeywordController@search')->name('keywords.search');
Route::get('keywords/export', 'KeywordController@export')->name('keywords.export');
Route::get('keywords/{keyword}/show', 'KeywordController@show')->name('keywords.show');
Route::post('keywords/{keyword}/remove-mms', 'KeywordController@removeMMS')->name('keywords.remove-mms');
Route::post('keywords/batch_action', 'KeywordController@batchAction')->name('keywords.batch_action');

Route::resource('keywords', 'KeywordController', [
        'only' => ['index', 'create', 'store', 'update', 'destroy'],
]);


/*
|--------------------------------------------------------------------------
| Sender id module
|--------------------------------------------------------------------------
|
| Route for sender id and sender id plan module
|
*/

Route::post('senderid/search', 'SenderIDController@search')->name('senderid.search');
Route::get('senderid/export', 'SenderIDController@export')->name('senderid.export');
Route::get('senderid/{senderid}/show', 'SenderIDController@show')->name('senderid.show');
Route::post('senderid/{senderid}/active', 'SenderIDController@activeToggle')->name('senderid.active');
Route::post('senderid/batch_action', 'SenderIDController@batchAction')->name('senderid.batch_action');
Route::resource('senderid', 'SenderIDController', [
        'only' => ['index', 'create', 'store', 'update', 'destroy'],
]);

Route::get('senderid/plan', 'SenderIDController@plan')->name('senderid.plan');
Route::post('senderid/search-plan', 'SenderIDController@searchPlan')->name('senderid.search_plan');

routes/web.php
<?php

use App\Http\Controllers\LanguageController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {

    if (config('app.stage') == 'new') {
        return redirect('install');
    }

    if (config('app.stage') == 'Live' && config('app.version') == '2.8') {
        return redirect('update');
    }

    return redirect('login');
});

// locale Route
Route::get('lang/{locale}', [LanguageController::class, 'swap']);
Route::any('languages', [LanguageController::class, 'languages'])->name('languages');

Route::get('test', function (){
    event(new \App\Events\MessageReceived('hello world'));
});

app/Http/Controllers/Customer/BlacklistsController.php
<?php

namespace App\Http\Controllers\Customer;

use App\Http\Requests\Blacklists\StoreBlacklist;
use App\Models\Blacklists;
use App\Repositories\Contracts\BlacklistsRepository;
use Illuminate\Auth\Access\AuthorizationException;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\View\View;

class BlacklistsController extends CustomerBaseController
{
    protected $blacklists;


    /**
     * BlacklistsController constructor.
     *
     * @param  BlacklistsRepository  $blacklists
     */

    public function __construct(BlacklistsRepository $blacklists)
    {
        $this->blacklists = $blacklists;
    }

    /**
     * @return Application|Factory|View
     * @throws AuthorizationException
     */

    public function index()
    {

        $this->authorize('view_blacklist');

        $breadcrumbs = [
                ['link' => url("dashboard"), 'name' => __('locale.menu.Dashboard')],
                ['name' => __('locale.menu.Blacklist')],
        ];

        return view('customer.Blacklists.index', compact('breadcrumbs'));
    }


    /**
     * @param  Request  $request
     *
     * @return void
     * @throws AuthorizationException
     */
    public function search(Request $request)
    {

        $this->authorize('view_blacklist');

        $columns = [
                0 => 'uid',
                1 => 'number',
                2 => 'reason',
                3 => 'uid',
        ];

        $totalData = Blacklists::where('user_id', Auth::user()->id)->count();

        $totalFiltered = $totalData;

        $limit = $request->input('length');
        $start = $request->input('start');
        $order = $columns[$request->input('order.0.column')];
        $dir   = $request->input('order.0.dir');

        if (empty($request->input('search.value'))) {
            $blacklists = Blacklists::where('user_id', Auth::user()->id)->offset($start)
                    ->limit($limit)
                    ->orderBy($order, $dir)
                    ->get();
        } else {
            $search = $request->input('search.value');

            $blacklists = Blacklists::where('user_id', Auth::user()->id)->whereLike(['uid', 'number', 'reason'], $search)
                    ->offset($start)
                    ->limit($limit)
                    ->orderBy($order, $dir)
                    ->get();

            $totalFiltered = Blacklists::where('user_id', Auth::user()->id)->whereLike(['uid', 'number', 'reason'], $search)->count();

        }

        $data = [];
        if ( ! empty($blacklists)) {
            foreach ($blacklists as $blacklist) {

                if ($blacklist->reason) {
                    $reason = $blacklist->reason;
                } else {
                    $reason = '--';
                }

                $nestedData['uid']    = $blacklist->uid;
                $nestedData['number'] = $blacklist->number;
                $nestedData['reason'] = $reason;
                $nestedData['action'] = "<span class='action-delete text-danger' data-id='$blacklist->uid'><i class='feather us-2x icon-trash'></i></span>";
                $data[]               = $nestedData;

            }
        }

        $json_data = [
                "draw"            => intval($request->input('draw')),
                "recordsTotal"    => intval($totalData),
                "recordsFiltered" => intval($totalFiltered),
                "data"            => $data,
        ];

        echo json_encode($json_data);
        exit();

    }


    /**
     * @return Application|Factory|View
     * @throws AuthorizationException
     */

    public function create()
    {
        $this->authorize('create_blacklist');

        $breadcrumbs = [
                ['link' => url("dashboard"), 'name' => __('locale.menu.Dashboard')],
                ['link' => url('blacklists'), 'name' => __('locale.menu.Blacklist')],
                ['name' => __('locale.blacklist.add_new_blacklist')],
        ];

        return view('customer.Blacklists.create', compact('breadcrumbs'));
    }


    /**
     * @param  StoreBlacklist  $request
     *
     * @return RedirectResponse
     */

    public function store(StoreBlacklist $request): RedirectResponse
    {

        if (config('app.env') == 'demo') {
            return redirect()->route('customer.blacklists.index')->with([
                    'status'  => 'error',
                    'message' => 'Sorry! This option is not available in demo mode',
            ]);
        }


        $this->blacklists->store($request->input());

        return redirect()->route('customer.blacklists.index')->with([
                'status'  => 'success',
                'message' => __('locale.blacklist.blacklist_successfully_added'),
        ]);

    }

    /**
     * @param  Blacklists  $blacklist
     *
     * @return JsonResponse
     *
     * @throws AuthorizationException
     */
    public function destroy(Blacklists $blacklist): JsonResponse
    {
        if (config('app.env') == 'demo') {
            return response()->json([
                    'status'  => 'error',
                    'message' => 'Sorry! This option is not available in demo mode',
            ]);
        }


        $this->authorize('delete_blacklist');

        $this->blacklists->destroy($blacklist);

        return response()->json([
                'status'  => 'success',
                'message' => __('locale.blacklist.blacklist_successfully_deleted'),
        ]);

    }

    /**
     * Bulk Action with Enable, Disable and Delete
     *
     * @param  Request  $request
     *
     * @return JsonResponse
     * @throws AuthorizationException
     */

    public function batchAction(Request $request): JsonResponse
    {
        if (config('app.env') == 'demo') {
            return response()->json([
                    'status'  => 'error',
                    'message' => 'Sorry! This option is not available in demo mode',
            ]);
        }

        $action = $request->get('action');
        $ids    = $request->get('ids');

        switch ($action) {
            case 'destroy':
                $this->authorize('delete_blacklist');

                $this->blacklists->batchDestroy($ids);

                return response()->json([
                        'status'  => 'success',
                        'message' => __('locale.blacklist.blacklists_deleted'),
                ]);

        }

        return response()->json([
                'status'  => 'error',
                'message' => __('locale.exceptions.invalid_action'),
        ]);

    }

}

resources/views/customer/SendingServer/list.blade.php
@extends('layouts/contentLayoutMaster')

@section('title', __('locale.menu.Sending Servers'))

@section('vendor-style')
    {{-- vendor files --}}
    <link rel="stylesheet" href="{{ asset(mix('vendors/css/tables/datatable/datatables.min.css')) }}">
@endsection
@section('page-style')
    {{-- Page css files --}}
    <link rel="stylesheet" href="{{ asset(mix('css/pages/data-list-view.css')) }}">
@endsection

@section('content')
    {{-- Data list view starts --}}
    <section id="data-list-view" class="data-list-view-header">
        {{-- DataTable starts --}}
        <div class="table-responsive">
            <table class="table data-list-view">
                <thead>
                <tr>
                    <th></th>
                    <th>{{__('locale.labels.name')}}</th>
                    <th>{{__('locale.labels.type')}}</th>
                    <th>{{__('locale.labels.actions')}}</th>
                </tr>
                </thead>
                <tbody>
                @foreach ($sending_servers as $server)
                    @if($server["type"] === 'http')
                        @php $color = "success" @endphp
                    @elseif($server["type"] === 'smpp')
                        @php $color = "primary" @endphp
                    @elseif($server["type"] === 'whatsapp')
                        @php $color = "info" @endphp
                    @endif

                    @if($server['custom'] == 1)
                        @php $type = 'custom' @endphp
                    @else
                        @php $type = $server->settings @endphp
                    @endif

                    <tr>
                        <td></td>
                        <td>{{ $server['name'] }}</td>
                        <td>
                            <div class="chip chip-{{$color}}">
                                <div class="chip-body">
                                    <div class="chip-text">{{ strtoupper($server['type'])}}</div>
                                </div>
                            </div>
                        </td>
                        <td>
                            <a href="{{route('customer.sending-servers.create', ['type' => $type])}}" class="btn btn-primary btn-sm">{{__('locale.labels.choose')}}</a>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
        {{-- DataTable ends --}}

    </section>
    <br>
    {{-- Data list view end --}}
@endsection
@section('vendor-script')
    {{-- vendor js files --}}
    <script src="{{ asset(mix('vendors/js/tables/datatable/datatables.min.js')) }}"></script>
    <script src="{{ asset(mix('vendors/js/tables/datatable/datatables.buttons.min.js')) }}"></script>
    <script src="{{ asset(mix('vendors/js/tables/datatable/datatables.bootstrap4.min.js')) }}"></script>
    <script src="{{ asset(mix('vendors/js/tables/datatable/buttons.bootstrap.min.js')) }}"></script>
@endsection
@section('page-script')
    <script>
        $(document).ready(function () {
            "use strict"
            // init list view datatable

            $(".data-list-view").DataTable({

                "processing": true,
                "columns": [
                    {"data": "id", orderable: false, searchable: false},
                    {"data": "name"},
                    {"data": "type"},
                    {"data": "action", orderable: false, searchable: false}
                ],
                responsive: false,
                columnDefs: [
                    {
                        orderable: false,
                        searchable: false,
                        targets: 0,
                    }
                ],
                dom:
                    '<"top"<"actions action-btns"B><"action-filters"lf>><"clear">rt<"bottom"<"actions">p>',
                oLanguage: {
                    sLengthMenu: "_MENU_",
                    sZeroRecords: "{{ __('locale.datatables.no_results') }}",
                    sSearch: "",
                    sProcessing: "{{ __('locale.datatables.processing') }}",
                    oPaginate: {
                        sFirst: "{{ __('locale.datatables.first') }}",
                        sPrevious: "{{ __('locale.datatables.previous') }}",
                        sNext: "{{ __('locale.datatables.next') }}",
                        sLast: "{{ __('locale.datatables.last') }}"
                    }
                },
                aLengthMenu: [[10, 20, 50, 100], [10, 20, 50, 100]],
                order: [[0, "asc"]],
                bInfo: false,
                pageLength: 10,
                buttons: [],
                initComplete: function () {
                    $(".dt-buttons .btn").removeClass("btn-secondary")
                }
            });

            // To append actions dropdown before add new button
            let actionDropdown = $(".add-new-div")
            actionDropdown.insertBefore($(".top .actions .dt-buttons"))

            // Scrollbar
            if ($(".data-items").length > 0) {
                new PerfectScrollbar(".data-items", {wheelPropagation: false})
            }

        });

    </script>
@endsection